version: "3"

services:
  app:
    build: ./docker-config/app
    ports:
      - ${APP_PORT}:4000
    command: mix phx.server
    tty: true
    volumes:
      - ./src:/app/src
    working_dir: /app/src

  db:
    build: ./docker-config/db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
